version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Release

# environment:
#   sonarqubetoken:
#     secure: ppdeirHI9dsM7NpQgtwIRqXbiqhJZvIyHxOFhnME5HhRFS6IbYZqRppQi7fTqv37

before_build:
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity n
  - cmd: nuget restore
  - choco install opencover.portable
  - choco install codecov
  - choco install xunit
  - choco install "msbuild-sonarqube-runner" -y
  - choco install 7zip

build_script:
  - cmd: dotnet build -c Release
  - cmd: dotnet publish DeveMultiCompressor\DeveMultiCompressor.csproj -c Release -r win10-x64

after_build:
  #- ps: .\Scripts\GoRepack.ps1
  - cmd: 7z a -t7z -m0=LZMA2 -mmt=on -mx9 -md=1536m -mfb=273 -ms=on -mqs=on -sccUTF-8 "Scripts\Output\DeveMultiCompressor.7z" "DeveMultiCompressor\bin\Release\netcoreapp2.2\win10-x64\publish\*"

test_script:
  #- SonarScanner.MSBuild.exe begin /k:"DeveImageOptimizer" /o:"devedse-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarqubetoken% /d:sonar.cs.opencover.reportsPaths=".\DeveImageOptimizer.Coverage.xml" /d:sonar.coverage.exclusions="DeveImageOptimizer.ConsoleApp/**/*.cs,DeveImageOptimizer.Tests/**/*.cs"
  #- cmd: dotnet build -c Release
  #- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test .\DeveImageOptimizer.Tests\DeveImageOptimizer.Tests.csproj -c Release --filter ShouldSkipForAppVeyor!=Yes" -oldstyle -returntargetcode -output:.\DeveImageOptimizer.Coverage.xml -filter:"+[DeveImageOptimizer*]* -[DeveImageOptimizer.Tests*]*"
  #- SonarScanner.MSBuild.exe end /d:sonar.login=%sonarqubetoken%
  #- codecov -f "DeveImageOptimizer.Coverage.xml"
  - cmd: dotnet test -c Release

artifacts:
  - path: Scripts\Output\*.7z
    name: droppackage

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: droppackage
