version: 1.0.{build}
skip_tags: true
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: Scripts\GoRepack.cmd
artifacts:
- path: Scripts\DeveMultiCompressor.7z
  name: droppackage7z
- path: Scripts\DeveMultiCompressor.zip
  name: droppackagezip
deploy:
- provider: GitHub
  auth_token:
    secure: CMLxtDi0SaeuWVHdknn/e+aHOvIy9DanPxnrSLEeuwia5RQ9RPwQ5qtkJ7x0DvJF
  artifact: droppackage